[tool.black]
line-length = 88
include = '\.pyi?$'
exclude = '''
/(
    .git
  | .hg
  | .mypy_cache
  | .tox
  | venv
  | _build
  | buck-out
  | build
  | dist
  | .pytest
)/
'''

[tool.isort]
# make it compatible with black
profile = "black" 