name: Run unit tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.12
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install coverage
      - name: Run tests
        run: coverage run -m unittest discover apptests
      - name: Show coverage report
        run: coverage report -m

    env:
      GoogleAPI: ${{ secrets.GoogleAPI }}
      